/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApplicationSuccessRouteImport } from './routes/application-success'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PositionsIdRouteImport } from './routes/positions/$id'
import { Route as AdminPositionsIndexRouteImport } from './routes/admin/positions/index'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin/applications/index'
import { Route as AdminPositionsNewRouteImport } from './routes/admin/positions/new'
import { Route as AdminPositionsIdRouteImport } from './routes/admin/positions/$id'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin/applications/$id'

const ApplicationSuccessRoute = ApplicationSuccessRouteImport.update({
  id: '/application-success',
  path: '/application-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PositionsIdRoute = PositionsIdRouteImport.update({
  id: '/positions/$id',
  path: '/positions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPositionsIndexRoute = AdminPositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPositionsNewRoute = AdminPositionsNewRouteImport.update({
  id: '/positions/new',
  path: '/positions/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPositionsIdRoute = AdminPositionsIdRouteImport.update({
  id: '/positions/$id',
  path: '/positions/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/application-success': typeof ApplicationSuccessRoute
  '/positions/$id': typeof PositionsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/positions/$id': typeof AdminPositionsIdRoute
  '/admin/positions/new': typeof AdminPositionsNewRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/positions': typeof AdminPositionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application-success': typeof ApplicationSuccessRoute
  '/positions/$id': typeof PositionsIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/positions/$id': typeof AdminPositionsIdRoute
  '/admin/positions/new': typeof AdminPositionsNewRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/positions': typeof AdminPositionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/application-success': typeof ApplicationSuccessRoute
  '/positions/$id': typeof PositionsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/positions/$id': typeof AdminPositionsIdRoute
  '/admin/positions/new': typeof AdminPositionsNewRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/positions/': typeof AdminPositionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/application-success'
    | '/positions/$id'
    | '/admin/'
    | '/admin/applications/$id'
    | '/admin/positions/$id'
    | '/admin/positions/new'
    | '/admin/applications'
    | '/admin/positions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application-success'
    | '/positions/$id'
    | '/admin'
    | '/admin/applications/$id'
    | '/admin/positions/$id'
    | '/admin/positions/new'
    | '/admin/applications'
    | '/admin/positions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/application-success'
    | '/positions/$id'
    | '/admin/'
    | '/admin/applications/$id'
    | '/admin/positions/$id'
    | '/admin/positions/new'
    | '/admin/applications/'
    | '/admin/positions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplicationSuccessRoute: typeof ApplicationSuccessRoute
  PositionsIdRoute: typeof PositionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/application-success': {
      id: '/application-success'
      path: '/application-success'
      fullPath: '/application-success'
      preLoaderRoute: typeof ApplicationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/positions/$id': {
      id: '/positions/$id'
      path: '/positions/$id'
      fullPath: '/positions/$id'
      preLoaderRoute: typeof PositionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/positions/': {
      id: '/admin/positions/'
      path: '/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AdminPositionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/positions/new': {
      id: '/admin/positions/new'
      path: '/positions/new'
      fullPath: '/admin/positions/new'
      preLoaderRoute: typeof AdminPositionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/positions/$id': {
      id: '/admin/positions/$id'
      path: '/positions/$id'
      fullPath: '/admin/positions/$id'
      preLoaderRoute: typeof AdminPositionsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
  AdminPositionsIdRoute: typeof AdminPositionsIdRoute
  AdminPositionsNewRoute: typeof AdminPositionsNewRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
  AdminPositionsIndexRoute: typeof AdminPositionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
  AdminPositionsIdRoute: AdminPositionsIdRoute,
  AdminPositionsNewRoute: AdminPositionsNewRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
  AdminPositionsIndexRoute: AdminPositionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplicationSuccessRoute: ApplicationSuccessRoute,
  PositionsIdRoute: PositionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
